#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "header.h"
#include "sysdep.h"

/* Output to the text window via gprint in sysdep*.c */

int preventoutput=0;

void output (char *s)
{	
	if (preventoutput) return;
	if (outputbuffer)
	{   
		if (outputbuffererror) return;
		if (outputbuffer+strlen(s)>=outputbufferend)
		{	outputbuffererror=1; return;
		}
		strcpy(outputbuffer,s);
		outputbuffer+=strlen(s);
		return;
	}
	text_mode();
	if (outputing || error) gprint(s);
	if (outfile)
	{	fprintf(outfile,"%s",s);
		if (ferror(outfile))
		{	output("Error on dump file.\n");
			error=200;
			fclose(outfile); outfile=0;
		}
	}
}

void print (char *s, ...)
{	
	char text [MAXLINE];
	va_list v;
	if (preventoutput) return;
	text_mode();
	va_start(v,s);
	vsprintf(text,s,v);
	if (outputbuffer)
	{	
		output(text); return;
	}
	if (outputing || error) gprint(text);
	if (outfile)
	{   
		fprintf(outfile,text);
		if (ferror(outfile))
		{	output("Error on dump file.\n");
			error=200;
			fclose(outfile); outfile=0;
		}
	}
}

void println (char *s, ...)
{
	char text [MAXLINE];
	va_list v;
	if (preventoutput) return;
	text_mode();
	va_start(v,s);
	vsprintf(text,s,v);
	strcat(text,"\n");
	if (outputbuffer)
	{	
		output(text); return;
	}
	if (outputing || error) gprint(text);
	if (outfile)
	{   
		fprintf(outfile,text);
		if (ferror(outfile))
		{	output("Error on dump file.\n");
			error=200;
			fclose(outfile); outfile=0;
		}
	}
}

void output1 (char *s, ...)
{	
	char text [MAXLINE];
	va_list v;
	if (preventoutput) return;
	text_mode();
	va_start(v,s);
	vsprintf(text,s,v);
	if (outputbuffer)
	{	output(text); return;
	}
	if (outputing || error) gprint(text);
	if (outfile)
	{   fprintf(outfile,text);
		if (ferror(outfile))
		{	output("Error on dump file.\n");
			error=200;
			fclose(outfile); outfile=0;
		}
	}
}

int output1hold (int f, char *s, ...)
{	static char text [1024];
	ULONG si;
	va_list v;
	if (f==0) text[0]=0;
	text_mode();
	va_start(v,s);
	vsprintf(text+strlen(text),s,v);
	if (f<=0) return strlen(text);
	si=strlen(text);
	if (si<(ULONG)f)
	{	memmove(text+(f-si),text,si+1);
		memset(text,' ',f-si);
	}
	if (outputbuffer)
	{	output(text); return strlen(text);
	}
	if (outputing || error) gprint(text);
	if (outfile)
	{   fprintf(outfile,text);
		if (ferror(outfile))
		{	output("Error on dump file.\n");
			error=200;
			fclose(outfile); outfile=0;
		}
	}
	return strlen(text);
}

/* Print an error message */

extern char *type_udfline (char *start);

#define min(a,b) ((a<b)?(a):(b))

void print_error (char *p)
{	
	int i;
	if (errorout) return;
	if (input_line<=p && input_line+1024>p)
	{	
		int maxl=linelength-8;
		int k=min(maxl*4/5,(int)(p-input_line));
		char out[MAXLINE];
		strcpy(out,p-k);
		out[maxl]=0;
		print("Error in:\n");
		if (p-k>input_line) { print("... "); k+=4; }
		print("%s",out);
		if ((int)strlen(out)<linelength) print(" ...");
		print("\n");
		for (i=0; i<k; i++) output(" ");
		output("^\n");
		notify_error(input_line);
	}
	else if (udfon && error!=ERROR_USER)
	{	
		notify_error(udfline);
	}
	else
	{
		print("\nError generated by error() command\n\n");
	}
	errorout=1;
}


